set(_CATKIN_CURRENT_PACKAGE "hiwin_description")
set(hiwin_description_VERSION "0.0.0")
set(hiwin_description_MAINTAINER "HIWIN Technologies Corp <hiwin_robot@hiwin.tw>")
set(hiwin_description_PACKAGE_FORMAT "2")
set(hiwin_description_BUILD_DEPENDS )
set(hiwin_description_BUILD_EXPORT_DEPENDS )
set(hiwin_description_BUILDTOOL_DEPENDS "catkin")
set(hiwin_description_BUILDTOOL_EXPORT_DEPENDS )
set(hiwin_description_EXEC_DEPENDS "joint_state_publisher_gui" "robot_state_publisher" "rviz" "urdf" "xacro")
set(hiwin_description_RUN_DEPENDS "joint_state_publisher_gui" "robot_state_publisher" "rviz" "urdf" "xacro")
set(hiwin_description_TEST_DEPENDS "roslaunch")
set(hiwin_description_DOC_DEPENDS )
set(hiwin_description_URL_WEBSITE "")
set(hiwin_description_URL_BUGTRACKER "")
set(hiwin_description_URL_REPOSITORY "https://github.com/HIWINCorporation/hiwin_ros.git")
set(hiwin_description_DEPRECATED "")