set(_CATKIN_CURRENT_PACKAGE "hiwin_driver")
set(hiwin_driver_VERSION "0.0.0")
set(hiwin_driver_MAINTAINER "HIWIN Technologies Corp <hiwin_robot@hiwin.tw>")
set(hiwin_driver_PACKAGE_FORMAT "2")
set(hiwin_driver_BUILD_DEPENDS "industrial_robot_status_interface" "control_msgs" "controller_manager" "hardware_interface" "pluginlib" "pass_through_controllers" "roscpp" "std_srvs")
set(hiwin_driver_BUILD_EXPORT_DEPENDS "control_msgs" "controller_manager" "hardware_interface" "pluginlib" "pass_through_controllers" "roscpp" "std_srvs")
set(hiwin_driver_BUILDTOOL_DEPENDS "catkin")
set(hiwin_driver_BUILDTOOL_EXPORT_DEPENDS )
set(hiwin_driver_EXEC_DEPENDS "industrial_robot_status_controller" "joint_state_controller" "robot_state_publisher" "industrial_robot_client" "control_msgs" "controller_manager" "hardware_interface" "pluginlib" "pass_through_controllers" "roscpp" "std_srvs")
set(hiwin_driver_RUN_DEPENDS "industrial_robot_status_controller" "joint_state_controller" "robot_state_publisher" "industrial_robot_client" "control_msgs" "controller_manager" "hardware_interface" "pluginlib" "pass_through_controllers" "roscpp" "std_srvs")
set(hiwin_driver_TEST_DEPENDS )
set(hiwin_driver_DOC_DEPENDS )
set(hiwin_driver_URL_WEBSITE "")
set(hiwin_driver_URL_BUGTRACKER "")
set(hiwin_driver_URL_REPOSITORY "https://github.com/HIWINCorporation/hiwin_ros.git")
set(hiwin_driver_DEPRECATED "")