# CMake generated Testfile for 
# Source directory: /home/ROS/workspace/src/industrial_core/simple_message
# Build directory: /home/ROS/workspace/build_isolated/simple_message
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_simple_message_gtest_utest "/home/ROS/workspace/build_isolated/simple_message/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ROS/workspace/build_isolated/simple_message/test_results/simple_message/gtest-utest.xml" "--return-code" "/home/ROS/workspace/devel_isolated/simple_message/lib/simple_message/utest --gtest_output=xml:/home/ROS/workspace/build_isolated/simple_message/test_results/simple_message/gtest-utest.xml")
set_tests_properties(_ctest_simple_message_gtest_utest PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/ROS/workspace/src/industrial_core/simple_message/CMakeLists.txt;130;catkin_add_gtest;/home/ROS/workspace/src/industrial_core/simple_message/CMakeLists.txt;0;")
add_test(_ctest_simple_message_gtest_utest_byte_swapping "/home/ROS/workspace/build_isolated/simple_message/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ROS/workspace/build_isolated/simple_message/test_results/simple_message/gtest-utest_byte_swapping.xml" "--return-code" "/home/ROS/workspace/devel_isolated/simple_message/lib/simple_message/utest_byte_swapping --gtest_output=xml:/home/ROS/workspace/build_isolated/simple_message/test_results/simple_message/gtest-utest_byte_swapping.xml")
set_tests_properties(_ctest_simple_message_gtest_utest_byte_swapping PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/ROS/workspace/src/industrial_core/simple_message/CMakeLists.txt;134;catkin_add_gtest;/home/ROS/workspace/src/industrial_core/simple_message/CMakeLists.txt;0;")
add_test(_ctest_simple_message_gtest_utest_float64 "/home/ROS/workspace/build_isolated/simple_message/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ROS/workspace/build_isolated/simple_message/test_results/simple_message/gtest-utest_float64.xml" "--return-code" "/home/ROS/workspace/devel_isolated/simple_message/lib/simple_message/utest_float64 --gtest_output=xml:/home/ROS/workspace/build_isolated/simple_message/test_results/simple_message/gtest-utest_float64.xml")
set_tests_properties(_ctest_simple_message_gtest_utest_float64 PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/ROS/workspace/src/industrial_core/simple_message/CMakeLists.txt;138;catkin_add_gtest;/home/ROS/workspace/src/industrial_core/simple_message/CMakeLists.txt;0;")
add_test(_ctest_simple_message_gtest_utest_udp "/home/ROS/workspace/build_isolated/simple_message/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/ROS/workspace/build_isolated/simple_message/test_results/simple_message/gtest-utest_udp.xml" "--return-code" "/home/ROS/workspace/devel_isolated/simple_message/lib/simple_message/utest_udp --gtest_output=xml:/home/ROS/workspace/build_isolated/simple_message/test_results/simple_message/gtest-utest_udp.xml")
set_tests_properties(_ctest_simple_message_gtest_utest_udp PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/noetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/ROS/workspace/src/industrial_core/simple_message/CMakeLists.txt;142;catkin_add_gtest;/home/ROS/workspace/src/industrial_core/simple_message/CMakeLists.txt;0;")
subdirs("gtest")
