set(_CATKIN_CURRENT_PACKAGE "pass_through_controllers")
set(pass_through_controllers_VERSION "0.0.0")
set(pass_through_controllers_MAINTAINER "HIWIN Technologies Corp <hiwin_robot@hiwin.tw>")
set(pass_through_controllers_PACKAGE_FORMAT "2")
set(pass_through_controllers_BUILD_DEPENDS "control_msgs" "controller_interface" "hardware_interface" "pluginlib" "roscpp" "realtime_tools" "trajectory_msgs")
set(pass_through_controllers_BUILD_EXPORT_DEPENDS "control_msgs" "controller_interface" "hardware_interface" "pluginlib" "roscpp" "realtime_tools" "trajectory_msgs")
set(pass_through_controllers_BUILDTOOL_DEPENDS "catkin")
set(pass_through_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(pass_through_controllers_EXEC_DEPENDS "control_msgs" "controller_interface" "hardware_interface" "pluginlib" "roscpp" "realtime_tools" "trajectory_msgs")
set(pass_through_controllers_RUN_DEPENDS "control_msgs" "controller_interface" "hardware_interface" "pluginlib" "roscpp" "realtime_tools" "trajectory_msgs")
set(pass_through_controllers_TEST_DEPENDS )
set(pass_through_controllers_DOC_DEPENDS )
set(pass_through_controllers_URL_WEBSITE "")
set(pass_through_controllers_URL_BUGTRACKER "")
set(pass_through_controllers_URL_REPOSITORY "https://github.com/HIWINCorporation/hiwin_ros.git")
set(pass_through_controllers_DEPRECATED "")