set(_CATKIN_CURRENT_PACKAGE "hiwin_ra610_1476_moveit_config")
set(hiwin_ra610_1476_moveit_config_VERSION "0.3.0")
set(hiwin_ra610_1476_moveit_config_MAINTAINER "HIWIN Technologies Corp <hiwin_robot@hiwin.tw>")
set(hiwin_ra610_1476_moveit_config_PACKAGE_FORMAT "1")
set(hiwin_ra610_1476_moveit_config_BUILD_DEPENDS )
set(hiwin_ra610_1476_moveit_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "hiwin_description")
set(hiwin_ra610_1476_moveit_config_BUILDTOOL_DEPENDS "catkin")
set(hiwin_ra610_1476_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(hiwin_ra610_1476_moveit_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "hiwin_description")
set(hiwin_ra610_1476_moveit_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "hiwin_description")
set(hiwin_ra610_1476_moveit_config_TEST_DEPENDS )
set(hiwin_ra610_1476_moveit_config_DOC_DEPENDS )
set(hiwin_ra610_1476_moveit_config_URL_WEBSITE "http://moveit.ros.org/")
set(hiwin_ra610_1476_moveit_config_URL_BUGTRACKER "https://github.com/moveit/moveit/issues")
set(hiwin_ra610_1476_moveit_config_URL_REPOSITORY "https://github.com/moveit/moveit")
set(hiwin_ra610_1476_moveit_config_DEPRECATED "")